### ISSUE TITLE
Incomplete Submission

### ISSUE THREAD

**Issue by codepathreview** [LinkCable/codepath-hw-movies#1]
Hi,

It looks like you have not created an issue for your submission. Please create an issue for all future project submissions following the steps in the submission guide

Also, your gif does not appear to render correctly in your README file. Please make sure your gif renders within your README file for future assignments. Check the README template for syntax for displaying animated gif files.

After all, it's great to see your work done!

:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- It looks like you duplicate the code of sending network request twice: one in `viewDidLoad()` and another in `refreshMovieList()`. I believe you can make a network request once and reuse your code in other functions.
- Your coding style is quite inconsistent. Sometimes you use semicolon at the end and sometimes you don't. Although in Swift using both is okay, I suggest you should stick to one style. You can check [here](https://github.com/github/swift-style-guide) and [here](https://github.com/raywenderlich/swift-style-guide) for Swift style & convention guides.
- This is a small tip: you can use deselectRowAtIndexPath after tableView:didSelectRowAtIndexPath: in order to deselect a given row.

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

One of the most important part of these projects is that you add additional features and tweak the UI / UX because that will provide many more learning opportunities. I would encourage you to complete the projects each week with required stories early and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_ios/feedback_guides_swift/project_1_feedback) which covers the most common points we see for this project. Read through the feedback guide point-by-point to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at support@codepath.com.

**Comment by phil-kt** [comment]
I don't know why the gif isn't showing, it's the same exact format as the other README. http://i.imgur.com/CjYmEPA.gif

Thanks for the feedback! I didn't actually intend for this to get graded yet as I was going to do some of the optional stuff and clean up the code.

**Comment by phil-kt** [comment]
@codepathreview second week of the app is up

**Comment by codepathreview** [comment]
Hello there,

I almost thought you once again forgot to create a new issue for your second-week project. I think it would be better if you could create a separate issue for the second week, although the project is still the same. 

:+1: Nice work! The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways. Below is my feedback:
- I just look back at your code of the first week. There are 2 errors: 

1) The assignment requires that **User sees an error message when there's a networking error** and **You may not use UIAlertController to display the error.** That means that you have to integrate your own `UIView` in order to show the error (like this [picture](http://forums.androidcentral.com/attachments/google-nexus-10-tablet/51236d1355614625t-facebook-network-error-no-internet-connection-screenshot_2012-12-15-15-15-05.png))

2) When I launched the app with no Internet connection. The spinning indicator kept spinning forever. I believe you can easily find a way to fix this little bug.
- About the app icon, you can follow this [guide](https://developer.apple.com/library/ios/recipes/xcode_help-image_catalog-1.0/chapters/AddingLaunchImagestoanAssetCatalog.html) to add an app icon 

So far so good, we have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

Have a nice day. :smile:

**Comment by phil-kt** [comment]
@codepathreview thanks, I fixed the two errors
